import type { PortfolioContent } from './types'

export const portfolioContent: PortfolioContent = {
  owner: {
    name: 'Ghaida',
    fullName: "Ghaida Ja'aysah",
    email: 'hello@ghaida.dev',
    role: 'Computer Systems Engineer · Front-End Developer',
  },
  navItems: ['work', 'playground', 'path', 'about'],
  heroWords: ['interfaces', 'experiences', 'ideas', 'solutions'],
  projects: [
    { number: '01', title: 'ThemeSolve', type: 'AI × Education', award: '1st place — PLwG Spark Hackathon', text: 'A personalized math problem rewriting experience designed to make difficult questions feel approachable.', stack: 'React · AI · UX research', tone: 'bg-[#6A4951]' },
    { number: '02', title: 'Systems in motion', type: 'Interface experiment', award: 'A study in calm interactions', text: 'Exploring how motion, hierarchy, and thoughtful feedback can make complex systems feel human.', stack: 'Next.js · Motion · Prototyping', tone: 'bg-[#574830]' },
    { number: '03', title: 'Small useful things', type: 'Open playground', award: 'Ongoing collection', text: 'Tiny experiments, creative layouts, and details worth keeping around.', stack: 'JavaScript · CSS · APIs', tone: 'bg-[#434F03]' },
  ],
  path: [
    {
      id: 'exalt',
      organization: 'EXALT',
      title: 'Front-End Intern',
      category: 'experience',
      year: '2025',
      description: [
        'Gained hands-on experience in software development using modern technologies and industry best practices.',
        'Worked collaboratively on real-world projects within agile teams and experienced a professional development workflow.',
        'Improved problem-solving, debugging, and code quality through mentorship, collaboration, and peer code reviews.',
      ],
      tags: ['Front-End', 'Agile', 'Code Review', 'Software Development'],
    },
    {
      id: 'datacamp',
      organization: 'DataCamp',
      title: 'DataCamp Program',
      category: 'program',
      year: '2025',
      description: [
        'Completed interactive learning experiences focused on Python, SQL, and R for data analysis and visualization.',
        'Applied data science concepts through hands-on exercises and projects.',
      ],
      tags: ['Python', 'SQL', 'R', 'Data Analysis'],
    },
    {
      id: 'zakey-tech',
      organization: 'Zakey Tech',
      title: 'Deep Dive LLM Bootcamp',
      category: 'program',
      year: '2025',
      description: [
        'Learned the fundamentals of Large Language Models, including their architecture, training concepts, and applications.',
        'Built and explored LLM-based applications such as chatbots, text generation, and sentiment analysis.',
      ],
      tags: ['LLMs', 'AI', 'NLP'],
    },
    {
      id: 'udacity',
      organization: 'Udacity',
      title: 'AI Programming with Python & TensorFlow Nanodegree',
      category: 'program',
      year: '2025',
      description: [
        'Learned Python, NumPy, Pandas, and Matplotlib for data analysis and visualization.',
        'Built and trained deep learning models using TensorFlow and neural networks.',
        'Applied machine learning concepts through practical projects such as image classification.',
      ],
      tags: ['Python', 'TensorFlow', 'Deep Learning', 'Machine Learning'],
    },
    {
      id: 'gsg-codecareer',
      organization: 'Gaza Sky Geeks',
      title: 'CodeCareer Training',
      category: 'training',
      year: '2025',
      description: ['Advanced JavaScript concepts, asynchronous programming, ES6+, React, APIs, component-based architecture, and clean code practices.'],
      tags: ['JavaScript', 'React', 'APIs', 'ES6+'],
    },
    {
      id: 'gsg-database-security',
      organization: 'Gaza Sky Geeks',
      title: 'Database Security Training',
      category: 'training',
      year: '2025',
      description: [
        'Completed 50 hours of Oracle database security training covering OLS, DAC, and user privilege management.',
        'Worked with controlled data access, secure database configurations, and multi-level security concepts.',
      ],
      tags: ['Oracle', 'Database Security', 'OLS', 'DAC'],
    },
    {
      id: 'prime-academy',
      organization: 'Prime Academy',
      title: 'Problem Solving Training',
      category: 'training',
      year: '2024',
      description: ['Developed problem-solving skills through algorithms and programming challenges.'],
      tags: ['Two Pointers', 'Greedy', 'Brute Force', 'Recursion', 'Dynamic Programming', 'Mathematical Problem Solving'],
      tagsLabel: 'Topics',
    },
    {
      id: 'knowledge-academy',
      organization: 'Knowledge Academy',
      title: 'Front-End Training',
      category: 'training',
      year: '2024',
      description: ['Hands-on training in HTML, CSS, media queries, responsive layouts, and user-friendly web interfaces.'],
      tags: ['HTML', 'CSS', 'Responsive Design'],
    },
  ],
  education: {
    school: 'Arab American University',
    degree: 'Computer Systems Engineering',
    period: '2021 — 2026',
    status: 'Graduated · 2026',
    gpa: '3.62',
    description: 'Five years of engineering, software, systems, projects, deadlines, debugging, and learning how things work beneath the interface.',
  },
  playground: [
    { text: 'A button that feels like a door.', className: 'items-end bg-[#987E29] font-serif text-2xl italic hover:-rotate-2' },
    { text: 'Hover to discover', className: 'items-center justify-center bg-[#6A4951] text-center font-sans text-xs uppercase tracking-[0.2em] text-[#F0E8CD] hover:rotate-2' },
    { text: 'Good details matter.', className: 'items-end bg-[#574830] font-serif text-2xl text-[#F0E8CD] hover:-translate-y-2' },
  ],
  thinkingSteps: ['Problem', 'Understand', 'Break it down', 'Design', 'Build', 'Improve'],
  tools: [
    { name: 'HTML' },
    { name: 'CSS' },
    { name: 'JavaScript' },
    { name: 'React', description: 'Building reusable, interactive interfaces that feel natural to use.' },
    { name: 'Next.js' },
    { name: 'Laravel' },
    { name: '.NET' },
    { name: 'Oracle APEX' },
    { name: 'Git' },
    { name: 'REST APIs' },
  ],
  defaultTool: 'React',
  defaultToolDescription: 'A tool I use to turn thoughtful ideas into useful digital experiences.',
  // Drop certificate images in /public/certificates and point `image` at them.
  certificates: [
    { title: 'Front-End Development', issuer: 'Meta', date: '2025', image: '/placeholder.jpg' },
    { title: 'React & Modern JavaScript', issuer: 'Coursera', date: '2025', image: '/placeholder.jpg' },
    { title: 'Computer Systems Engineering', issuer: 'University', date: '2025', image: '/placeholder.jpg' },
    { title: 'AI for Education', issuer: 'Google', date: '2025', image: '/placeholder.jpg' },
    { title: 'Web Design & UX', issuer: 'Udemy', date: '2025', image: '/placeholder.jpg' },
  ],
  currently: [
    { label: 'Building', value: 'New ideas' },
    { label: 'Learning', value: 'TypeScript' },
    { label: 'Exploring', value: 'Better systems' },
  ],
  socials: [
    { label: 'GitHub', href: 'https://github.com' },
    { label: 'LinkedIn', href: 'https://linkedin.com' },
  ],
}
