'use client'

import { useEffect, useState } from 'react'

const projects = [
  { number: '01', title: 'ThemeSolve', type: 'AI × Education', award: '1st place — PLwG Spark Hackathon', text: 'A personalized math problem rewriting experience designed to make difficult questions feel approachable.', stack: 'React · AI · UX research', tone: 'bg-[#6A4951]' },
  { number: '02', title: 'Systems in motion', type: 'Interface experiment', award: 'A study in calm interactions', text: 'Exploring how motion, hierarchy, and thoughtful feedback can make complex systems feel human.', stack: 'Next.js · Motion · Prototyping', tone: 'bg-[#574830]' },
  { number: '03', title: 'Small useful things', type: 'Open playground', award: 'Ongoing collection', text: 'Tiny experiments, creative layouts, and details worth keeping around.', stack: 'JavaScript · CSS · APIs', tone: 'bg-[#434F03]' },
]

const milestones = [
  ['2023', 'Started building for the web', 'The first experiments were small, but the curiosity was not.'],
  ['2024', 'Problem solving & software engineering', 'Learning to understand the system before rushing to the solution.'],
  ['2025', 'Front-end training & hackathons', 'Turning ideas into interfaces that people can actually use.'],
  ['2026', 'Computer Systems Engineering graduate', 'Still learning. Still making. Still asking better questions.'],
]

const certificates = ['Front-End Development', 'React & Modern JavaScript', 'Computer Systems Engineering', 'AI for Education', 'Web Design & UX']
const tools = ['HTML', 'CSS', 'JavaScript', 'React', 'Next.js', 'Laravel', '.NET', 'Oracle APEX', 'Git', 'REST APIs']

export default function Portfolio() {
  const [word, setWord] = useState(0)
  const [menuOpen, setMenuOpen] = useState(false)
  const [tool, setTool] = useState('React')
  const words = ['interfaces', 'experiences', 'ideas', 'solutions']

  useEffect(() => {
    const interval = window.setInterval(() => setWord((current) => (current + 1) % words.length), 2200)
    return () => window.clearInterval(interval)
  }, [])

  return (
    <main className="min-h-screen overflow-hidden bg-[#F0E8CD] text-[#434F03]">
      <header className="fixed inset-x-0 top-0 z-30 flex items-center justify-between px-6 py-6 mix-blend-multiply md:px-12">
        <a href="#top" className="font-sans text-sm font-bold tracking-[0.22em]">GHAIDA<span className="text-[#987E29]">.</span></a>
        <nav className="hidden gap-8 font-sans text-xs font-medium uppercase tracking-[0.16em] sm:flex" aria-label="Main navigation">
          {['work', 'journey', 'playground', 'about'].map((item) => <a key={item} className="transition-colors hover:text-[#987E29]" href={`#${item}`}>{item}</a>)}
        </nav>
        <button className="font-sans text-xs font-bold uppercase tracking-[0.16em] sm:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>Menu</button>
        <a href="mailto:hello@ghaida.dev" className="hidden font-sans text-xs font-bold uppercase tracking-[0.16em] underline decoration-[#987E29] underline-offset-4 sm:block">Let&apos;s talk</a>
      </header>
      {menuOpen && <nav className="fixed inset-0 z-20 flex flex-col items-center justify-center gap-8 bg-[#F0E8CD] font-serif text-5xl" aria-label="Mobile navigation">{['work', 'journey', 'playground', 'about'].map((item) => <a key={item} href={`#${item}`} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav>}

      <section id="top" className="relative flex min-h-screen items-center px-6 pb-20 pt-32 md:px-12">
        <div className="relative z-10 max-w-5xl"><p className="mb-8 font-sans text-xs font-semibold uppercase tracking-[0.28em] text-[#6A4951]">Computer Systems Engineer · Front-End Developer</p><h1 className="font-serif text-[clamp(4rem,11vw,10.5rem)] leading-[0.83] tracking-[-0.07em]">I build things<br /><em className="pl-[12vw] font-normal text-[#6A4951]">people enjoy</em><br />using<span className="text-[#987E29]">.</span></h1><div className="mt-12 flex items-center gap-4 font-sans text-sm text-[#574830]"><span className="inline-block h-px w-12 bg-[#987E29]" /> <span>Currently making <strong className="text-[#434F03]">{words[word]}</strong></span></div></div>
        <div aria-hidden="true" className="absolute right-[8%] top-[23%] hidden size-64 md:block lg:size-80"><div className="absolute inset-10 rotate-12 border border-[#987E29]" /><div className="absolute inset-14 -rotate-6 rounded-[48%_52%_60%_40%] bg-[#6A4951] opacity-90" /><div className="absolute inset-20 rounded-[60%_40%_45%_55%] bg-[#987E29] mix-blend-multiply" /><span className="absolute -bottom-8 left-0 font-serif text-3xl italic text-[#6A4951]">make it feel good</span></div>
        <a href="#work" className="absolute bottom-8 left-6 flex items-center gap-3 font-sans text-[10px] uppercase tracking-[0.2em] md:left-12"><span className="flex size-8 items-center justify-center rounded-full border border-[#574830]">↓</span> Explore</a>
      </section>

      <section id="work" className="bg-[#434F03] px-6 py-28 text-[#F0E8CD] md:px-12 md:py-40"><div className="mb-20 flex items-end justify-between border-b border-[#F0E8CD]/25 pb-5"><p className="font-sans text-xs uppercase tracking-[0.25em] text-[#987E29]">01 / Selected work</p><p className="hidden font-serif text-lg italic opacity-70 sm:block">A collection of useful things</p></div><div className="flex flex-col gap-5">{projects.map((project) => <article key={project.number} className="group grid gap-7 border-b border-[#F0E8CD]/25 py-10 md:grid-cols-[5rem_1.2fr_1fr] md:items-center md:py-14"><span className="font-sans text-xs text-[#987E29]">{project.number}</span><div><h2 className="font-serif text-5xl leading-none transition-transform duration-500 group-hover:translate-x-3 md:text-8xl">{project.title}</h2><p className="mt-5 max-w-md font-sans text-sm leading-relaxed text-[#F0E8CD]/65">{project.text}</p></div><div><p className={`mb-5 inline-block rounded-full px-3 py-1 font-sans text-[10px] uppercase tracking-[0.15em] text-[#F0E8CD] ${project.tone}`}>{project.award}</p><p className="font-sans text-xs uppercase tracking-[0.16em] text-[#987E29]">{project.type} · {project.stack}</p><a href="#contact" className="mt-8 inline-block font-sans text-xs uppercase tracking-[0.18em] underline decoration-[#987E29] underline-offset-4">Explore project →</a></div></article>)}</div></section>

      <section id="journey" className="grid gap-16 px-6 py-28 md:grid-cols-[1fr_2fr] md:px-24 md:py-40"><p className="font-sans text-xs font-semibold uppercase tracking-[0.25em] text-[#6A4951]">02 / My journey</p><div><h2 className="max-w-3xl font-serif text-5xl leading-[0.95] tracking-[-0.04em] md:text-8xl">Curious by nature.<br /><em className="font-normal text-[#6A4951]">Precise by practice.</em></h2><div className="mt-16 border-t border-[#574830]/25">{milestones.map(([year, title, text]) => <div key={year} className="grid gap-3 border-b border-[#574830]/25 py-7 md:grid-cols-[7rem_1fr]"><span className="font-sans text-sm text-[#987E29]">{year}</span><div><h3 className="font-serif text-2xl">{title}</h3><p className="mt-2 max-w-lg font-sans text-sm leading-relaxed text-[#574830]">{text}</p></div></div>)}</div></div></section>

      <section id="playground" className="border-y border-[#574830]/25 px-6 py-24 md:px-12 md:py-32"><div className="flex flex-col gap-12 md:flex-row md:items-end md:justify-between"><div><p className="mb-5 font-sans text-xs uppercase tracking-[0.25em] text-[#6A4951]">03 / Playground</p><h2 className="font-serif text-6xl tracking-[-0.05em] md:text-9xl">Make room<br /><em className="font-normal text-[#6A4951]">for wonder.</em></h2></div><p className="max-w-xs font-sans text-sm leading-relaxed text-[#574830]">Not everything I build needs to become a project. Tiny interactions, visual notes, and questions I am not done asking yet.</p></div><div className="mt-20 grid gap-4 sm:grid-cols-3"><div className="flex h-48 items-end bg-[#987E29] p-5 font-serif text-2xl italic transition-transform hover:-rotate-2">A button that feels like a door.</div><div className="flex h-48 items-center justify-center bg-[#6A4951] p-5 text-center font-sans text-xs uppercase tracking-[0.2em] text-[#F0E8CD] transition-transform hover:rotate-2">Hover to discover</div><div className="flex h-48 items-end bg-[#574830] p-5 font-serif text-2xl text-[#F0E8CD] transition-transform hover:-translate-y-2">Good details matter.</div></div></section>

      <section id="thinking" className="bg-[#574830] px-6 py-28 text-[#F0E8CD] md:px-24 md:py-36"><p className="mb-10 font-sans text-xs uppercase tracking-[0.25em] text-[#987E29]">04 / How I think</p><h2 className="max-w-4xl font-serif text-6xl leading-[0.88] md:text-9xl">Make it clear.<br /><em className="font-normal text-[#987E29]">Make it matter.</em></h2><div className="mt-20 grid gap-px bg-[#F0E8CD]/20 md:grid-cols-6">{['Problem', 'Understand', 'Break it down', 'Design', 'Build', 'Improve'].map((step, index) => <div key={step} className="bg-[#574830] p-5"><span className="font-sans text-xs text-[#987E29]">0{index + 1}</span><h3 className="mt-10 font-serif text-2xl">{step}</h3></div>)}</div></section>

      <section id="toolbox" className="px-6 py-28 md:px-24 md:py-36"><p className="mb-10 font-sans text-xs uppercase tracking-[0.25em] text-[#6A4951]">05 / My toolbox</p><div className="grid gap-12 md:grid-cols-[1fr_1.2fr]"><h2 className="font-serif text-6xl leading-[0.9] md:text-9xl">Tools for<br /><em className="font-normal text-[#6A4951]">thinking.</em></h2><div><div className="flex flex-wrap gap-2">{tools.map((item) => <button key={item} onClick={() => setTool(item)} className={`border px-4 py-3 font-sans text-xs uppercase tracking-[0.15em] transition-colors ${tool === item ? 'border-[#434F03] bg-[#434F03] text-[#F0E8CD]' : 'border-[#574830]/30 hover:border-[#987E29]'}`}>{item}</button>)}</div><div className="mt-10 border-t border-[#574830]/25 pt-6"><p className="font-serif text-3xl">{tool}</p><p className="mt-3 max-w-md font-sans text-sm leading-relaxed text-[#574830]">{tool === 'React' ? 'Building reusable, interactive interfaces that feel natural to use.' : `A tool I use to turn thoughtful ideas into useful digital experiences.`}</p></div></div></div></section>

      <section id="certificates" className="overflow-hidden bg-[#6A4951] px-6 py-28 text-[#F0E8CD] md:py-36"><p className="mb-10 font-sans text-xs uppercase tracking-[0.25em] text-[#987E29]">06 / Proof of curiosity</p><h2 className="font-serif text-6xl md:text-9xl">Things I&apos;ve<br /><em className="font-normal text-[#987E29]">learned.</em></h2><div className="mt-20 flex min-w-max gap-5">{certificates.map((certificate, index) => <div key={certificate} className={`flex h-56 w-64 rotate-${index % 2 ? '2' : '1'} flex-col justify-between border border-[#F0E8CD]/35 bg-[#F0E8CD] p-5 text-[#434F03] transition-transform hover:-translate-y-3 hover:rotate-0`}><span className="font-sans text-xs uppercase tracking-[0.18em]">Certificate 0{index + 1}</span><p className="font-serif text-2xl">{certificate}</p><span className="font-sans text-[10px] uppercase tracking-[0.18em] text-[#6A4951]">Ghaida Ja&apos;aysah · 2025</span></div>)}</div></section>

      <section id="about" className="px-6 py-28 md:px-24 md:py-36"><div className="grid gap-16 md:grid-cols-[1fr_2fr]"><p className="font-sans text-xs uppercase tracking-[0.25em] text-[#6A4951]">07 / Currently</p><div><h2 className="font-serif text-6xl leading-[0.9] md:text-9xl">Learning.<br />Building.<br /><em className="font-normal text-[#6A4951]">Exploring.</em></h2><p className="mt-12 max-w-xl font-sans text-lg leading-relaxed text-[#574830]">I&apos;m Ghaida — a Computer Systems Engineer who enjoys turning ideas into interfaces that feel simple, intuitive, and alive.</p><div className="mt-12 grid gap-6 border-t border-[#574830]/25 pt-6 sm:grid-cols-3"><div><span className="font-sans text-xs uppercase tracking-[0.15em] text-[#987E29]">Building</span><p className="mt-2 font-serif text-xl">New ideas</p></div><div><span className="font-sans text-xs uppercase tracking-[0.15em] text-[#987E29]">Learning</span><p className="mt-2 font-serif text-xl">TypeScript</p></div><div><span className="font-sans text-xs uppercase tracking-[0.15em] text-[#987E29]">Exploring</span><p className="mt-2 font-serif text-xl">Better systems</p></div></div></div></div></section>

      <footer id="contact" className="bg-[#434F03] px-6 py-28 text-[#F0E8CD] md:px-12 md:py-36"><div className="flex flex-col gap-20 md:flex-row md:items-end md:justify-between"><div><p className="mb-8 font-sans text-xs uppercase tracking-[0.25em] text-[#987E29]">08 / Contact</p><h2 className="font-serif text-6xl leading-[0.85] tracking-[-0.05em] md:text-9xl">Let&apos;s build<br /><em className="font-normal text-[#987E29]">something.</em></h2></div><div className="font-sans text-sm"><p className="mb-5 text-[#F0E8CD]/60">Have an idea, a problem, or something worth building?</p><a className="text-2xl underline decoration-[#987E29] underline-offset-8" href="mailto:hello@ghaida.dev">Start a conversation →</a><div className="mt-8 flex gap-5 text-xs uppercase tracking-[0.15em]"><a href="https://github.com" target="_blank" rel="noreferrer">GitHub</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">LinkedIn</a></div></div></div><div className="mt-24 flex justify-between border-t border-[#F0E8CD]/25 pt-5 font-sans text-[10px] uppercase tracking-[0.2em] text-[#F0E8CD]/60"><span>Ghaida Ja&apos;aysah © 2026</span><span>Made with curiosity &amp; code</span></div></footer>
    </main>
  )
}
